#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Running checks before committing'

# Check Prettier standards
npx pretty-quick --staged

# Check ESLint Standards
npm run lint ||
  (
    echo '😤 ESLint Check Failed. 😤 
    Make the required changes listed above, add changes and try to commit again.'
    false
  )

# Check tsconfig standards
npm run check-types ||
  (
    echo '❌ Failed Type check.❌
    Make the changes required above.'
    false
  )

echo 'Trying to build'

npm run build ||
  (
    echo '❌ Build failed ❌
    Check the errors above to see why. 
    '
    false
  )

echo '✅Can commit✅'
